### ISSUE TITLE
user deletion

### ISSUE THREAD

**Issue by ensei-tankado** [ensei-tankado/userauth#3]
while an account is deactivated it is to be deleted from the backend db also. For that the username will be send to an api for deletion

**Comment by ensei-tankado** [comment]
code on android side is completed

**Comment by ajmaln** [comment]
@ensei-tankado Approve the PR after verifying its working

**Comment by ajmaln** [comment]
Resolved by #4

**Comment by ensei-tankado** [comment]
solved
